install.packages('dplyr')
install.packages('plyr')
install.packages('zoo')
install.packages('ggplot2')

library(dplyr)
library(plyr)
library(zoo)
library(ggplot2)

dados<-select(covid,location,date,new_cases)
dados2<-filter(dados,location=="Brazil")
dados2<-slice(dados2,958:1017)
avg <- rollmean(dados2[3],as.integer(sqrt(count_(dados2))))
avg <- data.frame(avg)
grafico1 = ggplot(data = avg,aes(x=row(avg),y=new_cases))
tendenciamediamovel = grafico1+geom_point(size=2.5)+geom_smooth(fill=NA)
plot(tendenciamediamovel)
# Gerando dados estatísticos
summary(dados2[3])
summary(avg)
